{% set name = "guidata" %}
{% set version = "3.5.3" %}

package:
  name: guidata
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d37eb91b893a0c1fc2105b989a06c41d9044a458e236749f63d60f9370396898

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - h5py >=3.0
    - numpy >=1.21
    - qtpy >=1.9
    - requests
    - tomli
    - pyqt

test:
  imports:
    - guidata
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/PlotPyStack/guidata
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Automatic GUI generation for easy dataset editing and display with Python
  description: The guidata package is a Python library generating Qt graphical user interfaces. It is part of the PlotPyStack project, aiming at providing a unified framework for creating scientific GUIs with Python and Qt.
  doc_url: https://guidata.readthedocs.io
  dev_url: https://github.com/PlotPyStack/guidata

extra:
  recipe-maintainers:
    - marcelotrevisani
    - denivyruck
    - beenje
