{% set python_min = python_min|default("3.9") %}
{% set name = "guidata" %}
{% set version = "3.9.0" %}

package:
  name: guidata
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7032534993cd62622b220ac33d1a3eadb4cc4465691018a90aa907267e3404ea

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - h5py >=3.1
    - numpy >=1.21
    - qtpy >=1.9
    - requests
    - tomli
    - pyqt

test:
  imports:
    - guidata
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/PlotPyStack/guidata
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Automatic GUI generation for easy dataset editing and display with Python
  description: The guidata package is a Python library generating Qt graphical user interfaces. It is part of the PlotPyStack project, aiming at providing a unified framework for creating scientific GUIs with Python and Qt.
  doc_url: https://guidata.readthedocs.io
  dev_url: https://github.com/PlotPyStack/guidata

extra:
  recipe-maintainers:
    - marcelotrevisani
    - denivyruck
    - beenje
