{% set version = "1.7.8" %}

package:
  name: guidata
  version: {{ version }}

source:
  url: https://github.com/PierreRaybaut/guidata/archive/v{{ version }}.tar.gz
  sha256: 3ad51da3d863fd5d60a859b0c17c2b6396cbf826075e9e45f7a0cbef80305ee9
  patches:
    - removed_entry_points.patch
    # The correct imports should come from QtGui
    - qt_import.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - pyqt
    - sip
  run:
    - python
    - pyqt
    - sip

test:
  imports:
    - guidata

about:
  home: https://github.com/PierreRaybaut/guidata
  license: CECILL
  license_family: OTHER
  license_file: Licence_CeCILL_V2-en.txt
  summary: Automatic GUI generation for easy dataset editing and display with Python
  description: |
    Based on the Qt Python binding module PyQt4, guidata is a Python library
    generating graphical user interfaces for easy dataset editing and display.
    It also provides helpers and application development tools for PyQt4.
  doc_url: https://pythonhosted.org/guidata/
  dev_url: https://github.com/PierreRaybaut/guidata

extra:
  recipe-maintainers:
    - marcelotrevisani
    - denivyruck
