{% set version = "1.7.9" %}

package:
  name: guidata
  version: {{ version }}

source:
  url: https://github.com/PierreRaybaut/guidata/archive/v{{ version }}.tar.gz
  sha256: c0ff20c481f634d4d548bd56ae56572187007b26e18ba8692b767a02b7a39c68

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - qtpy >=1.3,<2.0
    - pyqt
  run:
    - python
    - qtpy >=1.3,<2.0
    - pyqt

test:
  imports:
    - guidata
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/PierreRaybaut/guidata
  license: CECILL
  license_family: OTHER
  license_file: Licence_CeCILL_V2-en.txt
  summary: Automatic GUI generation for easy dataset editing and display with Python
  description: |
    Based on the Qt Python binding module PyQt4, guidata is a Python library
    generating graphical user interfaces for easy dataset editing and display.
    It also provides helpers and application development tools for PyQt4.
  doc_url: https://pythonhosted.org/guidata/
  dev_url: https://github.com/PierreRaybaut/guidata

extra:
  recipe-maintainers:
    - marcelotrevisani
    - denivyruck
