{% set version = "2.0.4" %}

package:
  name: guidata
  version: {{ version }}

source:
  url: https://github.com/PierreRaybaut/guidata/archive/v{{ version }}.tar.gz
  sha256: 09b10883a215f91b14ce409b0a57718f1511c73ce8aa61f0f79dba52ae874b9e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - qtpy >=1.3
    - pyqt
  run:
    - python
    - qtpy >=1.3
    - pyqt

test:
  imports:
    - guidata
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/PierreRaybaut/guidata
  license: CECILL
  license_family: OTHER
  license_file: Licence_CeCILL_V2-en.txt
  summary: Automatic GUI generation for easy dataset editing and display with Python
  description: |
    Based on the Qt Python binding module PyQt4, guidata is a Python library
    generating graphical user interfaces for easy dataset editing and display.
    It also provides helpers and application development tools for PyQt4.
  doc_url: https://pythonhosted.org/guidata/
  dev_url: https://github.com/PierreRaybaut/guidata

extra:
  recipe-maintainers:
    - marcelotrevisani
    - denivyruck
